import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { TooltipProvider } from "@/components/ui/tooltip";

import "./globals.css";

const nunitoSans = Nunito({
  subsets: ["latin"],
  weight: ["400", "600", "700", "800"],
  display: "swap",
  variable: "--font-nunito",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

console.log("nunitoSans", nunitoSans);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${nunitoSans.variable}`}>
      <body className="antialiased text-foreground">
        <TooltipProvider>{children}</TooltipProvider>
      </body>
    </html>
  );
}
